repos:
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        language_version: python3.13

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        language_version: python3.13
        additional_dependencies:
          - mypy>=1.18.2
          - types-requests>=2.32.4.20250913
          - sqlalchemy[asyncio]==2.0.41
          - asyncpg==0.30.0
          - aiohttp==3.13
          - aiosqlite>=0.21.0
          - pydantic>=2.12.4
        files: ^src/