services:
  twitch-bot:
    build: .
    container_name: twitch-bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./settings.ini:/app/settings.ini:rw
    environment:
      TZ: Europe/Moscow
      DATABASE_URL: postgresql+asyncpg://bot:botpassword@db/twitch_bot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:13
    container_name: twitch-db
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: botpassword
      POSTGRES_DB: twitch_bot
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot -d twitch_bot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  data:
